apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRY0R1Nm1CZjFzV2lRQWhENSt6Rlp6REFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRMll6azJaRGswWkMxbE9HWTBMVFE1TkRBdE9UWTBaaTB5TWpFd016RmlZemhoWWpZdwpJQmNOTWpVeE1UQTJNREl4TkRBM1doZ1BNakExTlRFd016QXdNekUwTURkYU1DOHhMVEFyQmdOVkJBTVRKRFpqCk9UWmtPVFJrTFdVNFpqUXRORGswTUMwNU5qUm1MVEl5TVRBek1XSmpPR0ZpTmpDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQUxGT1R0bVZFaWlsWWpUTy9ZekxCMjhrYUdIUVo1MStKTmhUZ3hRUQpKOGt3cFFwZnV4RHh6SmZiR0FkQWd0akVycVliVS9XeW5zd2ZNSlFxc2RtQjJlbndtR0JlZjA0WEdhNVprUXo3CjVNME9TaW93YncvVHFIb3cySnVpVllsZnlURmEwTlExK2xZOTFvQVloeGZrQ3dIdHJCdnY5YjU4TWhVS3B0OCsKd3dVTWZEYU04ZmUvV2hkZnB3NnhadzQ2T0diQklnWk1keHlCM1lLcGEvYlBNaXRHdG8xbEVJSEFXdjBmUG1aagpKRWx5bVQxZ0hnWXc0QUdYU1pYblBjWW5zZC9vNm5ETHUwRVU1MlNpS3Y5ZW9MdllrV2loa3hyd3hCaTVDMHB2ClQydVpBUnJmaXNaTDBWUURIV0FJQkEvMUU0MkNkcC94Nk9YVGNVRk5URkx0OWRwYkZjcmxmOUh6N1RvM3d3MkkKQnZHN2plSUlZU2srTTN6NmQ0VlYvcDVPV2xGbmUrSERVME5EMktBRWw4U2VsWFYxUk5uckdmbEV1ZFpSRVdUbApCZnlDSHBLUERJQUwwRUl5WGJoSGgyTmlBUmJKb0UxZDB3bEdmbS9YanRNUGQ1Qi9XcjljaGwwK3FSUUZRZHdMCkEwc3Y4NS9RRXlDb1lodlFDdkJTYlNOa0hRSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVU3MFJDY2RIOEgyRjFVMTMwN3hzamo2M3plczh3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFJLytyTkxhaXdlSVdzd0xxQXYzODNXNkRCY04reno2dEFYRmZQUWYxa05TCnp0TEZQZUV5TGtzS1ZsOTdhQ3hoYWp0QzdjNHZZQUpWQUdIcDgxOFFiU3c5a0VxbHEyV01qM3FTbzhPQ2hEWWwKUTlrN0VZNXE0dGpuRk9tckpxeittWnRoSmFPRTFFL0t1UHZJMlFUeXMrZ3lYY3JtcldnWUFQM29jczNzcWNHcgplRjM0Vjg2cUtPUXByNDFCM2FYeEZGYnFpUnoyR2ltdERodzRsOVIyVFlLWFNObTY5YzRPRTdtaDk1SFJKYWl2CkJPTHN5cTFhU1V1aHRpTm9tWHJXUXhhSTB5aEVSZXlORUJEUFBLYm9uYm12R21MeFpoMWthY1puak5VODhhRmYKdTFIcGtnQ2VGVHB3L1IrdWpzc2JVR0haWG11NDlhNVUrVE54RXFDbjB4UnZDYW5oR3I4S1RBTEx4OHR4a0c0cwp4RmR0SWtYaXNsaDI2YUVNQVhxZ1ZHOXcvUzlTVEZheEFycUlTUitjUXhYZzNUVXlBMUFucUZpeWR3Mng5TGdjClRPRFRmQWpmQkpJbE1ZTXBzeXJvcW1qZHFObytSUDJKTGdLRFJLOEltcFRBWEYwMzRCQWxxVGp1UW1SMjc0TUMKa1Jrd2xNZ2FNTFFQd3NCdFdZNzRCQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://136.119.41.60
  name: chat-pulimi_us-central1-c_helloworld-688573b
contexts:
- context:
    cluster: chat-pulimi_us-central1-c_helloworld-688573b
    user: chat-pulimi_us-central1-c_helloworld-688573b
  name: chat-pulimi_us-central1-c_helloworld-688573b
current-context: chat-pulimi_us-central1-c_helloworld-688573b
kind: Config
preferences: {}
users:
- name: chat-pulimi_us-central1-c_helloworld-688573b
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: gke-gcloud-auth-plugin
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      provideClusterInfo: true

