apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRSUV5WTRoL014aDk2QkJmUEU5bHpFekFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlSak1EUmtNV00zTWkxbU5qZzRMVFF6TnpRdE9XRm1OeTAyTnpNeFltWm1ZV1E0T1RRdwpJQmNOTWpVeE1UQTJNRFUwTVRRMVdoZ1BNakExTlRFd016QXdOalF4TkRWYU1DOHhMVEFyQmdOVkJBTVRKR013Ck5HUXhZemN5TFdZMk9EZ3RORE0zTkMwNVlXWTNMVFkzTXpGaVptWmhaRGc1TkRDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQU9MV3h2RDNUcVVGN290byttMW94RkVtRTJoY01BbERsRGsvTzdsawpPbDB4M0lXd04vcVFubm1QQ1BKdXQ3OG1ubkZwUzFBL1FnbUxzNHhrZnVzRGtGUWFrWENJNTlQajJJQWgwSE5xCkVVMDVJYVV6VWEzRlNteUFDa3dQcTBwZ2lqWGU4RGlESnlLdndnL2xnWFk2V3Y0VkpUOCt3bitHYmRXSndiM2YKL0xXbHNRbktTcjFsWHFPWG9WRE96aFllbVdsblVCQ0o3b2lzdXdRMU5NWTYyWDlsci9iL1FTangydllFZ3N5bgpGWTJHeCtXZW9lWHVyUkRCQVRORDJVTk5ZdW03bGVZV3BuazlSREFZSzBnMEZVNFcyS2hmSzNUNHZ5eEVicTdYClpPMUNSSG5VVy9WdU5zZzM3azFVZ3JOVGxnZ3JDbGc5dmJLT0FOODJQdjluTmNFTEVDZmRhZ09wM3JhVGlrbzkKSFpHT04vc05LVis5anp6ODhRM21zYmYydmNtODRTWk96WitkUFhqaUIreWs4MWl1V3FJTW9DLzZrZjZINWdFQwpTNHdxU3FDZlovQ3IvQk5XdGdzNnB2SytZVDF1Ynl3THBCSkFUTjFWc1JGenM5ejZzZVdBcHRWaUszdU1oNUNhCkErU3dyTGp3QW5YWkZwdjlUUUUvYktSenN3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVBTGV1MmRLWlJoTGNsZWZXQWl6TWl6dVExOTh3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFKcXYweUR4bkZkcTFjZVdOQ1h2d1EyUXBhSUJmdjJ0WnhqSzBlSTBTYVVWCnc3NkpZZTF4UEllcDlzbnAvbjNTV0d0NUd4UEJCOEQ3WDlqMTU5YlJZcndrMEJuYXRTbDNYZlRDZW96aHd0dzIKTmJZYnZHbXRwemx4VXV2U0l2UGlUZ3djRjdjeXY2WndRaGpkMVVZSzZhNlNiVlo2UlNaNTMzNUJEWW9Rb21HSgpMOVNtK1JsdHYrL2xWK0hqWTdrWlhBbE1SQjRXek12QWxJaWRnWERVYlduc2JQcWZhRHpnQ3ovUGdnUDhJa1p2CmJHQVN5UnNScjY4RERFM2VpM2pIaFpLUGxsNmZpWk4vY2h4ZC9iRVBtSUdnaUJSZ3VwWHF4dFpIMFppd2RlOWEKS3o4cVhCb3Y2VVRxNmVENGlkVkpLSjRjWEhpWGVYeXYwSnVodkdaRStPVWUvWFZOQkRFVUZoTm42OXprQjZTUwpoOHcxcjQ4eWlwOFZITm5odnB6alBNbXBjUHRUbGpRRG9ZK1dSdTlUQWhWc0tPREtUS2t6dzhtdnE0TFl3NXZhCm1QcGhFSERuRzZpVlR5T0tZbXM5a2ZWSWRYdXBKQ1BjY2h2UXUvS3VKQjZOaW5MVXIyV1loalk4TTREU09YcW4KRDFXdXUzQ0YvKzVkMy9KeW1VMmt2UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://136.119.165.198
  name: chat-pulimi_us-central1-c_helloworld-7fbe279
contexts:
- context:
    cluster: chat-pulimi_us-central1-c_helloworld-7fbe279
    user: chat-pulimi_us-central1-c_helloworld-7fbe279
  name: chat-pulimi_us-central1-c_helloworld-7fbe279
current-context: chat-pulimi_us-central1-c_helloworld-7fbe279
kind: Config
preferences: {}
users:
- name: chat-pulimi_us-central1-c_helloworld-7fbe279
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: gke-gcloud-auth-plugin
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      provideClusterInfo: true
      env:
      - name: USE_GKE_GCLOUD_AUTH_PLUGIN
        value: "True"

