  apiVersion: v1
  clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQU01ODVpaDg3Vm5hdXRmcjFER1plNFF3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa05UaGxPRFV6TWpNdE1qaGpaaTAwWW1Wa0xXRm1aRGN0TWpBek5EZzJPVGM1WmpJNQpNQ0FYRFRJMU1UQXlOVEU0TXpreE0xb1lEekl3TlRVeE1ERTRNVGt6T1RFeldqQXZNUzB3S3dZRFZRUURFeVExCk9HVTROVE15TXkweU9HTm1MVFJpWldRdFlXWmtOeTB5TURNME9EWTVOemxtTWprd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FDMGZaK01aTU5hQmdnT0tHRExKaGJnUDVwOFRCelVEbkc0VjRYNwpZR0NPcVQxVEJxa1hTT3M3SVlsMWQwc3Y0bG5JY3pQWXoyTnl4UHhndDFmdDlnbDRFRTBzRGZnRkZKWVVPdm5pCkEyOHJuT2l6Tk1FSnN4K3hpVzEweE5FL2YvMUV2bXYrcTB2eFl5U05PNmoyYmxsSHRNQVNGWXBRaXIyYk9wKzcKdE5IZUR4QWZZSGdPOVUwTUE1MlM2a2tTZm1CNzZueG85RUJ3T01wQkU3QzJoMk9wTWJzaWpmaVIxaG5WNWxyagpVUkNYTHZkZVFKU0hzT0tNRjVtLzVVbVZobUQvZnJrSTE0bVJLL1NQZ2dtbEp0Q2lPSTZQRVRUNXUzdjMrU0RsCjZUMUZXSnlqZDdjdkFmcVVEcmVnV20yVmZncTBScjFJalZESVY4YjFzenZvYXZxQTN1UFlaYk8zRXVOVlVnU3MKcGJkVDlvRkgrMlpWdGZoRkkrd2N5SFVGdHJ6NFRvYWZSTlNyTWE2MkdOeHpSWEhGUEFsV0hrVjBTaVZYbWRNVApjRExPNkRpVkt4bUxBRUJnU0g3YVA0K04rQ1J4VFR0MW9iZkl3cVB1VkMyOXVtSXhPeFFMcDBya0d0dG0xbWR5Cm9TdUlOMzJ4UC9LaVFxNk1pSzM3UkxwdWNYOENBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGSFdjczlGRlBRVERuNkxsczlXVmtQc1VyaWxTTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRQklJOXVYZmI3bTBNaTBZZGhuQ3I3Vm05cEwvSWJrUWNDenJ1dzY5UGFnCkJnOTdieXpjU3psS3BRbXlSMFYvVHdLSlNVY3hBaWhKa0lmRjdoc0ROUm00SGJGeWNhYncrU3M4KzRDdFdGK1IKZDZwdmc4UEJiZll3OGFUcG1QOHVqSWhMbzBELzVNNEVBZFQrQmJsNlp4akpJeUhXa21acU9reFIrbmZiVG5kagpPc3VIUUlZdHJlZG9HUSs3WE5ndHNIZzNXbTFvR0QxaC9kZDNodFZ1M1J4YnVaWERWUE1NdDN5akxNY1dqRTV5CnRpbmVEUFg0RkpLK2JrTkhCWEFEbGRMV1NaQWtwNk5CT2RzSUVTOWNqdGU2ZVh6anBia1dHakRsN2RtSytoT1oKNld3WFFRcXQ4VXNoU3puUDRNQzFvbnFrdG8xUHFFVmtvdTA3M1NEUk1LQ1Njc0VzOHNoZldtemFqV0hQVUZYSgpvZEdvVHBlUlAwUE01cnNLOGw3SkRTSlF2R0EweDNrVEVDQTNxUjZuQVpHK1pDcXdoSFRObFdzRTQzQkFIb3FyClVmV2NqVmRNTm1MN2UwQUNCQmNtaEVtYUlHbE81emhYSnB0YzcreWV1WUdBelNDZ2Y2dzhNUnZJdVpNVG9LTlMKOWErRDArTWpiR1E2QW5peGxybEVaREE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://34.172.187.92
    name: chat-pulimi_us-central1-c_helloworld-52a8668
  contexts:
  - context:
      cluster: chat-pulimi_us-central1-c_helloworld-52a8668
      user: chat-pulimi_us-central1-c_helloworld-52a8668
    name: chat-pulimi_us-central1-c_helloworld-52a8668
  current-context: chat-pulimi_us-central1-c_helloworld-52a8668
  kind: Config
  preferences: {}
  users:
  - name: chat-pulimi_us-central1-c_helloworld-52a8668
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        command: gke-gcloud-auth-plugin
        installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
          https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
        provideClusterInfo: true

